name: IPTV优化系统

on:
  schedule:
    # 每天凌晨2点和下午2点运行
    - cron: '0 6,18 * * *'  # UTC时间，对应北京时间14:00和次日02:00
  workflow_dispatch:  # 允许手动触发

jobs:
  optimize_iptv:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行IPTV优化系统
        run: |
          cd tv
          python optimization_runner.py
        
      - name: 列出生成的文件
        run: |
          echo "===== 输出目录结构 ====="
          ls -la tv/output/
          echo "===== 增强播放列表 ====="
          ls -la tv/output/enhanced_playlists/
          echo "===== 统计数据 ====="
          cat tv/output/optimization_stats.json || echo "统计数据文件不存在"

      - name: 清理临时文件
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -type f -name "*.pyc" -delete 2>/dev/null || true
          find . -type f -name "*.log" -delete 2>/dev/null || true

      - name: 检查是否有更改
        id: detect_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git status
          git diff --cached --exit-code
        continue-on-error: true

      - name: 提交并推送更改
        if: steps.detect_changes.outcome != 'success'
        run: |
          git commit -m "更新IPTV优化结果 $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin master || git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
